name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: utube/process-service

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: |
          dotnet nuget add source --username abdurrahim373 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/letslearn373/index.json"
          dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

  docker-publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner  }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{github.repository}}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"